name: flutter_launcher
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  device_apps: ^2.2.0
  one_clock: ^1.0.9
  provider: ^6.1.1
  azlistview: ^2.0.0
  android_intent_plus: ^4.0.3
  battery_plus: ^4.0.2
  url_launcher: ^6.1.14
  system_theme: ^2.3.1
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/
